# Ian McGraw

SHELL = /bin/sh

.SUFFIXES:
.SUFFIXES: .hpp .cpp .c .h .o

ROOTDIR = ../..
include $(ROOTDIR)/src/Makefile.config

all: 
	cd $(LIBSRCDIR) && $(MAKE)

clean:
	cd $(LIBSRCDIR) && $(MAKE) clean
