# this will look better if viewed as -*- makefile -*-
SHELL = /bin/sh

include $(ROOTDIR)/src/Makefile.libraries

.SUFFIXES: .hpp .cpp .c .h .o

GPP=g++


INCDIR = $(SRCDIR)/include

SRCDIR = $(ROOTDIR)/src
LIBSRCDIR = $(SRCDIR)/lib
EXASRCDIR = $(SRCDIR)/examples
TSTSRCDIR = $(SRCDIR)/tests
LEARNSRCDIR = $(SRCDIR)/learn
BINSRCDIR = $(SRCDIR)/bin

BLDDIR = $(ROOTDIR)/build

LIBBLDDIR = $(BLDDIR)/lib
EXABLDDIR = $(BLDDIR)/examples
TSTBLDDIR = $(BLDDIR)/tests
LEARNBLDDIR = $(BLDDIR)/learn
BINBLDDIR = $(BLDDIR)/bin

LIBBASE = libLoopyInf.a 
LIBLEARN = libFastInfLearn.a
LIBFILES = $(LEARNBLDDIR)/$(LIBLEARN) $(LIBBLDDIR)/$(LIBBASE)
LIB = -L$(BLDDIR)/lib -L$(BLDDIR)/learn -L$(GSLDIR)/.libs  -L$(GSLDIR)/cblas/.libs  -L$(GLPKDIR)/lib \
      -lFastInfLearn -lgsl -lgslcblas -lLoopyInf -lglpk

DBGCPPFLAGS = #-g # -ggdb #-fno-inline #-pg #-g3 
WRNCPPFLAGS = -Wall -Wno-deprecated
OPTCPPFLAGS = -O2

INCLUDES = -I$(INCDIR) -I$(BOOSTDIR) -I$(GSLDIR) -I$(GLPKDIR)/include

CPPFLAGS = $(WRNCPPFLAGS) $(OPTCPPFLAGS)
CPPFLAGS += $(DBGCPPFLAGS)
CPPFLAGS += $(INCLUDES)
